#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = false


# ...
[vars]
CF-Access-Client-Id = "95bff2dd1e6ae9768ce8c00eae64401e.access"
CF-Access-Client-Secret = "cfast_V4HRO8vIrE1dAvowM8HsYjuRM4RbOZunXMj1rLTf65938b06"
NODE_OPTIONS = "--max-old-space-size=8192"
# ...
