/*
  # Change chats.id from uuid to bigint to support numeric IDs

  This migration changes the chats table id column from uuid to bigint
  to match the numeric IDs generated by getNextId() (e.g., 9, 10, etc.)

  Note: This will convert any existing UUIDs to 0. If you have existing data,
  you may need to handle migration differently.
*/

-- Step 1: Drop the default value FIRST (before changing type)
ALTER TABLE chats ALTER COLUMN id DROP DEFAULT;

-- Step 2: Drop the primary key constraint
ALTER TABLE chats DROP CONSTRAINT IF EXISTS chats_pkey;

-- Step 3: Change the id column type from uuid to bigint
-- Convert existing UUIDs to numeric if they're already numeric strings, otherwise use 0
ALTER TABLE chats ALTER COLUMN id TYPE bigint USING (
  CASE
    WHEN id::text ~ '^[0-9]+$' THEN id::text::bigint
    ELSE 0
  END
);

-- Step 4: Re-add the primary key constraint
ALTER TABLE chats ADD PRIMARY KEY (id);

-- Note: workspace_id and created_by remain as uuid since they reference other tables
